// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package billing_data

import (
	"fmt"
)

type OutstandingData struct {
	LoanId      *string `thrift:"loan_id,1,optional" frugal:"1,optional,string" json:"loan_id,omitempty"`
	CustomerId  *string `thrift:"customer_id,2,optional" frugal:"2,optional,string" json:"customer_id,omitempty"`
	Outstanding *int64  `thrift:"outstanding,3,optional" frugal:"3,optional,i64" json:"outstanding,omitempty"`
}

func NewOutstandingData() *OutstandingData {
	return &OutstandingData{}
}

func (p *OutstandingData) InitDefault() {
}

var OutstandingData_LoanId_DEFAULT string

func (p *OutstandingData) GetLoanId() (v string) {
	if !p.IsSetLoanId() {
		return OutstandingData_LoanId_DEFAULT
	}
	return *p.LoanId
}

var OutstandingData_CustomerId_DEFAULT string

func (p *OutstandingData) GetCustomerId() (v string) {
	if !p.IsSetCustomerId() {
		return OutstandingData_CustomerId_DEFAULT
	}
	return *p.CustomerId
}

var OutstandingData_Outstanding_DEFAULT int64

func (p *OutstandingData) GetOutstanding() (v int64) {
	if !p.IsSetOutstanding() {
		return OutstandingData_Outstanding_DEFAULT
	}
	return *p.Outstanding
}
func (p *OutstandingData) SetLoanId(val *string) {
	p.LoanId = val
}
func (p *OutstandingData) SetCustomerId(val *string) {
	p.CustomerId = val
}
func (p *OutstandingData) SetOutstanding(val *int64) {
	p.Outstanding = val
}

func (p *OutstandingData) IsSetLoanId() bool {
	return p.LoanId != nil
}

func (p *OutstandingData) IsSetCustomerId() bool {
	return p.CustomerId != nil
}

func (p *OutstandingData) IsSetOutstanding() bool {
	return p.Outstanding != nil
}

func (p *OutstandingData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutstandingData(%+v)", *p)
}

var fieldIDToName_OutstandingData = map[int16]string{
	1: "loan_id",
	2: "customer_id",
	3: "outstanding",
}
