app_name: billing_engine
env: boe
rpc_port: 8888
http_port: 8080

db:
  driver: postgres
  host: billing_engine.postgres
  port: 5432
  user: postgres
  password: 123123
  db_name: postgres

redis:
  host: billing_engine.redis
  port: 6379
  password: ""
  db: 0
