// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"fmt"
)

type PageNumberPagination struct {
	PageNum  int32 `thrift:"page_num,1" frugal:"1,default,i32" json:"page_num"`
	PageSize int32 `thrift:"page_size,2" frugal:"2,default,i32" json:"page_size"`
	Total    int32 `thrift:"total,3" frugal:"3,default,i32" json:"total"`
}

func NewPageNumberPagination() *PageNumberPagination {
	return &PageNumberPagination{}
}

func (p *PageNumberPagination) InitDefault() {
}

func (p *PageNumberPagination) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *PageNumberPagination) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *PageNumberPagination) GetTotal() (v int32) {
	return p.Total
}
func (p *PageNumberPagination) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *PageNumberPagination) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *PageNumberPagination) SetTotal(val int32) {
	p.Total = val
}

func (p *PageNumberPagination) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageNumberPagination(%+v)", *p)
}

var fieldIDToName_PageNumberPagination = map[int16]string{
	1: "page_num",
	2: "page_size",
	3: "total",
}
