// Code generated by Kitex v0.15.0. DO NOT EDIT.
package billingengineservice

import (
	server "github.com/cloudwego/kitex/server"
	billing_engine "github.com/yosuarichel/billing-engine/kitex_gen/billing_engine"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler billing_engine.BillingEngineService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler billing_engine.BillingEngineService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
