-- ================================
-- Customers Table
-- ================================
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT PRIMARY KEY, -- ID will be generated from app
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,

    -- Audit Columns
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);

-- Comments
COMMENT ON TABLE customers IS 'Stores basic customer information';
COMMENT ON COLUMN customers.id IS 'Primary key of the customer, generated by application';
COMMENT ON COLUMN customers.name IS 'Full name of the customer';
COMMENT ON COLUMN customers.phone_number IS 'Customer phone number';
COMMENT ON COLUMN customers.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN customers.created_by IS 'User ID who created the record';
COMMENT ON COLUMN customers.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN customers.updated_by IS 'User ID who last updated the record';
COMMENT ON COLUMN customers.deleted_at IS 'Soft delete timestamp';
COMMENT ON COLUMN customers.deleted_by IS 'User ID who deleted the record';

-- Indexes
CREATE INDEX idx_customers_phone_number ON customers(phone_number);
CREATE INDEX idx_customers_name ON customers(name);