-- ================================
-- Loan Schedule Table
-- ================================
CREATE TABLE IF NOT EXISTS loan_schedule (
    id BIGINT PRIMARY KEY, -- ID will be generated from app
    loan_id BIGINT NOT NULL, -- Reference to loans.loan_id
    week_number INT NOT NULL,
    due_date DATE NOT NULL,
    amount NUMERIC(15,0) NOT NULL,
    is_paid BOOLEAN DEFAULT FALSE,

    -- Audit Columns
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);

-- Comments
COMMENT ON TABLE loan_schedule IS 'Stores weekly installment schedule for each loan';
COMMENT ON COLUMN loan_schedule.id IS 'Primary key, generated by application';
COMMENT ON COLUMN loan_schedule.loan_id IS 'Reference to loans.loan_id';
COMMENT ON COLUMN loan_schedule.week_number IS 'Week number in the loan term';
COMMENT ON COLUMN loan_schedule.due_date IS 'Due date of the installment';
COMMENT ON COLUMN loan_schedule.amount IS 'Installment amount for this week';
COMMENT ON COLUMN loan_schedule.is_paid IS 'Whether this installment is paid or not';
COMMENT ON COLUMN loan_schedule.created_at IS 'Timestamp when record was created';
COMMENT ON COLUMN loan_schedule.created_by IS 'User ID who created the record';
COMMENT ON COLUMN loan_schedule.updated_at IS 'Timestamp when record was last updated';
COMMENT ON COLUMN loan_schedule.updated_by IS 'User ID who last updated the record';
COMMENT ON COLUMN loan_schedule.deleted_at IS 'Soft delete timestamp';
COMMENT ON COLUMN loan_schedule.deleted_by IS 'User ID who deleted the record';

-- Indexes
CREATE INDEX idx_schedule_loan_id ON loan_schedule(loan_id);
CREATE INDEX idx_schedule_due_date ON loan_schedule(due_date);
CREATE INDEX idx_schedule_is_paid ON loan_schedule(is_paid);