-- ================================
-- Payments Table
-- ================================
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT PRIMARY KEY, -- ID will be generated from app
    loan_id BIGINT NOT NULL, -- Reference to loans.loan_id
    schedule_id BIGINT NOT NULL, -- Reference to loan_schedule.schedule_id
    payment_date DATE NOT NULL,
    amount NUMERIC(15,0) NOT NULL,

    -- Audit Columns
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);

-- Comments
COMMENT ON TABLE payments IS 'Stores payment transactions made by customers';
COMMENT ON COLUMN payments.id IS 'Primary key, generated by application';
COMMENT ON COLUMN payments.loan_id IS 'Reference to loans.loan_id';
COMMENT ON COLUMN payments.schedule_id IS 'Reference to loan_schedule.schedule_id';
COMMENT ON COLUMN payments.payment_date IS 'Date when payment was made';
COMMENT ON COLUMN payments.amount IS 'Payment amount made by customer';
COMMENT ON COLUMN payments.created_at IS 'Timestamp when record was created';
COMMENT ON COLUMN payments.created_by IS 'User ID who created the record';
COMMENT ON COLUMN payments.updated_at IS 'Timestamp when record was last updated';
COMMENT ON COLUMN payments.updated_by IS 'User ID who last updated the record';
COMMENT ON COLUMN payments.deleted_at IS 'Soft delete timestamp';
COMMENT ON COLUMN payments.deleted_by IS 'User ID who deleted the record';

-- Indexes
CREATE INDEX idx_payments_loan_id ON payments(loan_id);
CREATE INDEX idx_payments_schedule_id ON payments(schedule_id);
CREATE INDEX idx_payments_payment_date ON payments(payment_date);